#!/bin/bash

YEAR=$1
PATH_POP_DATA=$2
PATH_SMOD_DATA=$3
TABLE_NAME_POP=$4
TABLE_NAME_SMOD=$5

POSTGRES_USER=$6
POSTGRES_PASSWORD=$7
POSTGRES_HOST=$8
POSTGRES_PORT=$9
POSTGRES_DB=${10}

PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}"  -c "CREATE EXTENSION IF NOT EXISTS postgis;"
PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}"  -c "CREATE EXTENSION IF NOT EXISTS postgis_raster;"

echo "Loading data for year ${YEAR}..."

raster2pgsql -c -C -s 54009 -t auto -Y 1000 -l 2,4,8,16 "${PATH_POP_DATA}" "${TABLE_NAME_POP}" | PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}"
raster2pgsql -c -C -s 54009 -t auto -Y 1000 -l 2,4,8,16 "${PATH_SMOD_DATA}" "${TABLE_NAME_SMOD}" | PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}"

echo "Loading complete for ${YEAR}"