#!/bin/bash

PATH_COUNTRY_BORDER_DATA=$1
TABLE_NAME_COUNTRY_BORDER=$2
PATH_CROSSWALK_TO_WORLD_BANK_CODES=$3
TABLE_NAME_CROSSWALK_TO_WORLD_BANK_CODES=$4

POSTGRES_USER=$5
POSTGRES_PASSWORD=$6
POSTGRES_HOST=$7
POSTGRES_PORT=$8
POSTGRES_DB=$9

PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}" -f "${PATH_COUNTRY_BORDER_DATA}"
PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}" -c "ALTER TABLE \"CShapes-2.0\" RENAME TO ${TABLE_NAME_COUNTRY_BORDER};"

PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}" -c"CREATE TABLE ${TABLE_NAME_CROSSWALK_TO_WORLD_BANK_CODES} (cshape_code INTEGER, world_bank_code VARCHAR(3));"
PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}" -c"\COPY ${TABLE_NAME_CROSSWALK_TO_WORLD_BANK_CODES}(cshape_code, world_bank_code) FROM '${PATH_CROSSWALK_TO_WORLD_BANK_CODES}' DELIMITER ',' CSV HEADER;"

echo "Data loaded successfully."